[Database]
SERVER = localhost\SQLEXPRESS
DATABASE = sistemgestionvntsjg

; --- Para usar con Azure SQL (en la nube) ---
; Descomenta (borra el ';') y rellena las siguientes líneas.
; Si USERNAME y PASSWORD están presentes, el programa los usará.
; Si están comentados o vacíos, usará la conexión local de Windows.
;
; USERNAME =
; PASSWORD =